const express=require('express');const multer=require('multer');const path=require('path');const{createClient}=require('@supabase/supabase-js');
const app=express(),PORT=process.env.PORT||3000,PASS=process.env.ADMIN_PASSWORD||'shumodav',BUCKET=process.env.SUPABASE_BUCKET||'music';
const URL=process.env.SUPABASE_URL,KEY=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!URL||!KEY){console.error('НЕТ SUPABASE_URL / SUPABASE_SERVICE_ROLE_KEY');process.exit(1)}
const db=createClient(URL,KEY,{auth:{persistSession:false,autoRefreshToken:false}});
app.use(express.urlencoded({extended:true}));app.use(express.json());app.use(express.static(path.join(__dirname,'public')));
const admin=(req,res,next)=>{if((req.headers['x-admin-password']||req.body.password||req.query.password)!==PASS)return res.status(401).json({error:'НЕВЕРНЫЙ ПАРОЛЬ'});next()};
const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:100*1024*1024},fileFilter:(_,f,cb)=>cb(/^(audio)\//.test(f.mimetype)||/\.(mp3|wav|ogg|flac|m4a|aac)$/i.test(f.originalname)?null:new Error('НУЖЕН АУДИОФАЙЛ'))});
app.get('/api/news',async(_,res)=>{const{data,error}=await db.from('news').select('*').order('created_at',{ascending:false});if(error)return res.status(500).json({error:error.message});res.json(data||[])});
app.get('/api/tracks',async(_,res)=>{const{data,error}=await db.from('tracks').select('*').order('created_at',{ascending:false});if(error)return res.status(500).json({error:error.message});res.json((data||[]).map(t=>({...t,url:db.storage.from(BUCKET).getPublicUrl(t.file_path).data.publicUrl})))});
app.get('/api/settings',async(_,res)=>{const{data,error}=await db.from('site_settings').select('*').eq('id',1).single();if(error)return res.status(500).json({error:error.message});res.json(data)});
app.post('/api/news',admin,async(req,res)=>{const text=String(req.body.text||'').trim();if(!text)return res.status(400).json({error:'НОВОСТЬ ПУСТАЯ'});const{error}=await db.from('news').insert({text:text.slice(0,1000)});if(error)return res.status(500).json({error:error.message});res.json({ok:true})});
app.delete('/api/news/:id',admin,async(req,res)=>{const{error}=await db.from('news').delete().eq('id',req.params.id);if(error)return res.status(500).json({error:error.message});res.json({ok:true})});
app.post('/api/upload',admin,upload.single('music'),async(req,res)=>{try{if(!req.file)return res.status(400).json({error:'ФАЙЛ НЕ ПРИЕХАЛ'});const title=String(req.body.title||req.file.originalname).slice(0,200),artist=String(req.body.artist||'ШУМОДАВ').slice(0,200),description=String(req.body.description||'').slice(0,1000),name=Date.now()+'_'+req.file.originalname.replace(/[^a-zA-Zа-яА-ЯёЁ0-9._-]/g,'_');let{error}=await db.storage.from(BUCKET).upload(name,req.file.buffer,{contentType:req.file.mimetype||'audio/mpeg'});if(error)return res.status(500).json({error:error.message});({error}=await db.from('tracks').insert({title,artist,description,file_path:name}));if(error){await db.storage.from(BUCKET).remove([name]);return res.status(500).json({error:error.message})}res.json({ok:true})}catch(e){res.status(500).json({error:e.message})}});
app.delete('/api/tracks/:id',admin,async(req,res)=>{const{data,error}=await db.from('tracks').select('file_path').eq('id',req.params.id).single();if(error)return res.status(404).json({error:'ТРЕК НЕ НАЙДЕН'});await db.storage.from(BUCKET).remove([data.file_path]);const x=await db.from('tracks').delete().eq('id',req.params.id);if(x.error)return res.status(500).json({error:x.error.message});res.json({ok:true})});
app.post('/api/settings',admin,async(req,res)=>{const row={id:1,site_title:String(req.body.site_title||'ШУМОДАВ').slice(0,100),background_url:String(req.body.background_url||'').slice(0,2000),marquee_text:String(req.body.marquee_text||'').slice(0,1000),updated_at:new Date().toISOString()};const{error}=await db.from('site_settings').upsert(row);if(error)return res.status(500).json({error:error.message});res.json({ok:true})});
app.get('/admin',(_,res)=>res.sendFile(path.join(__dirname,'public','admin.html')));app.listen(PORT,()=>console.log('ШУМОДАВ 2.0: http://localhost:'+PORT));
